/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_qiaoyf_com_opengl_image_PNGInfoHandle */

#ifndef _Included_android_qiaoyf_com_opengl_image_PNGInfoHandle
#define _Included_android_qiaoyf_com_opengl_image_PNGInfoHandle
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_qiaoyf_com_opengl_image_PNGInfoHandle
 * Method:    initPNGHandle
 * Signature: (Ljava/lang/Object;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_android_qiaoyf_com_opengl_1image_PNGInfoHandle_initPNGHandle
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     android_qiaoyf_com_opengl_image_PNGInfoHandle
 * Method:    getWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_android_qiaoyf_com_opengl_1image_PNGInfoHandle_getWidth
  (JNIEnv *, jclass);

/*
 * Class:     android_qiaoyf_com_opengl_image_PNGInfoHandle
 * Method:    getHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_android_qiaoyf_com_opengl_1image_PNGInfoHandle_getHeight
  (JNIEnv *, jclass);

/*
 * Class:     android_qiaoyf_com_opengl_image_PNGInfoHandle
 * Method:    isOpaque
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_android_qiaoyf_com_opengl_1image_PNGInfoHandle_isOpaque
  (JNIEnv *, jclass);

/*
 * Class:     android_qiaoyf_com_opengl_image_PNGInfoHandle
 * Method:    glTexImage2D
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_android_qiaoyf_com_opengl_1image_PNGInfoHandle_glTexImage2D
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     android_qiaoyf_com_opengl_image_PNGInfoHandle
 * Method:    free
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_android_qiaoyf_com_opengl_1image_PNGInfoHandle_free
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
